### ISSUE TITLE
Docker image for running the Meteor application.

### ISSUE THREAD

**Issue by tmcphillips** [openskope/skope-deployment#17]

**Comment by Zodiase** [comment]
The published images can be found here: https://hub.docker.com/r/openskope/web-app/tags/

**Comment by tmcphillips** [comment]
I'm reopening this issue and editing the title to indicate that it refers to the particular version of the web-app image that goes into the first release to test.  We can use this issue to discuss the image as we proceed.

**Comment by Zodiase** [comment]
Title doesn't seem to have been modified.

**Comment by Zodiase** [comment]
Depend on milestone https://github.com/openskope/skope-interface/milestone/3

**Comment by Zodiase** [comment]
Resolved as of f8313a1d7601135123a9ef69f40e24bcf2c83692.

See https://hub.docker.com/r/openskope/web-app/tags/
