### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-deployment#29]
- [x] create signed certificate for staging
- [x] modify nginx configuration to redirect http requests to https

**Comment by abrin** [comment]
Let’s talk about this next week; I thought I had starred certs already

**Comment by jterstriep** [comment]
Upgraded the staging server to automatically redirect http requests to https.

**Comment by Zodiase** [comment]
I'm reopening this since the data (or urls specifically) in ElasticSearch has not been updated to use https. Please close this once it's done.

**Comment by Zodiase** [comment]
Also @jterstriep, it looks like the nginx redirection is doing something funny to my local instances running on `localhost:3000/app`. Could you explain the redirection logic or take a look at how it would affect a request coming from `http://localhost:3000/app` (the referrer) towards `http://localhost:3000/app/elastic/datasets/_search`? Somehow it gets redirected to `https://localhost/es/datasets/_search`.

**Comment by jterstriep** [comment]
Reclosing. From the production/staging standpoint this is working correctly. Create a new issue for localhost deployments. This probably warrants a discussion in the dev meeting.
