### ISSUE TITLE
Update DNS record for app.openskope.org to refer to production instance on Jetstream

### ISSUE THREAD

**Issue by tmcphillips** [openskope/skope-deployment#56]
I have confirmed that simply defining an A Record though the Namecheap SimpleDNS interface is sufficient to associate a host name and domain to a floating IP address on Jetstream.

**Comment by abrin** [comment]
let me know if this is something you need help on

**Comment by tmcphillips** [comment]
@abrin Thanks!  For now could you please assign the DNS name tacc-staging.openskope.org to 129.114.16.124?  This would allow us to make certain that https and the openskope.org certificate work on Jetstream.

**Comment by abrin** [comment]
done… will take some time to propogate

**Comment by tmcphillips** [comment]
Awesome, thank you.  I've configured the staging server on Jetstream for access via HTTP at http://tacc-staging.openskope.org and everything seems to work.  Now to get HTTPS working...

**Comment by abrin** [comment]
If you give me a way to ssh In, I can put the SSL certs in the appropriate place

**Comment by tmcphillips** [comment]
Thanks!  It looks like the certificate files I managed to copy off Nebula before it went down work:
https://tacc-staging.openskope.org

Now I just have to reindex the documents in Elasticsearch so that they refer to https endpoints for GeoServer and the timeseries service (no-referrer-when-downgrade policy I guess).

**Comment by tmcphillips** [comment]
Ok, tacc-staging is operational now using https.  I wasn't able to run the dsindex.py and dsloader.py scripts successfully against the running elasticsearch instance when the services were configured to use HTTPS, however.  So I rebuilt the index with HTTPS disabled, then reenabled HTTPS.

**Comment by tmcphillips** [comment]
@jterstriep What is the trick to getting the dsindex.py and dsloader.py scripts to work over HTTPS connections to Elasticsearch?  Is there a stealth Python package (like certifi) that I need to install, or an environment variable pointing to certificates I need to set?  I've had to temporarily restore HTTP access to ES to get these scripts to run.

**Comment by jterstriep** [comment]
HTTPS is terminated at the nginx server. Use the proxy
https://staging.openskope.org/es or whatever the host name is.

**Comment by tmcphillips** [comment]
I think that is what I have been doing, but still getting an error.  Here is what I try to do and the error message I get (note https endpoint for --es-url):

```
ubuntu@tacc-staging:~/dataset-utilities/skope_loader$ python dsindex.py \
../../Datasets/dataset-mapping.json --debug  \
--es-url https://tacc-staging.openskope.org/es/  \
--es-index datasets_v2 \
--alias datasets

DEBUG: dsindex.py: deleting index datasets_v2
Traceback (most recent call last):
File "dsindex.py", line 86, in <module>
main()
File "dsindex.py", line 51, in main
es.indices.delete(index=args.es_index, ignore=[400, 404])
File "/home/ubuntu/.local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
return func(*args, params=params, **kwargs)
File "/home/ubuntu/.local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 188, in delete
params=params)
File "/home/ubuntu/.local/lib/python2.7/site-packages/elasticsearch/transport.py", line 345, in perform_request
data = self.deserializer.loads(data, headers_response.get('content-type'))
File "/home/ubuntu/.local/lib/python2.7/site-packages/elasticsearch/serializer.py", line 79, in loads
raise SerializationError('Unknown mimetype, unable to deserialize: %s' % mimetype)
elasticsearch.exceptions.SerializationError: Unknown mimetype, unable to deserialize: text/html
```

Once I enable http access via nginx.conf I can do the following without error (note http endpoint for --es-url):

```
ubuntu@tacc-staging:~/dataset-utilities/skope_loader$ python dsindex.py \
../../Datasets/dataset-mapping.json --debug \   
--es-url http://tacc-staging.openskope.org/es/ \
--es-index datasets_v2                         \
--alias datasets

DEBUG: dsindex.py: creating index datasets_v2
DEBUG: dsindex.py: index datasets_v2 created
DEBUG: dsindex.py: applying alias datasets to index
```

**Comment by tmcphillips** [comment]
@abrin I've created a new VM instance on Jetstream for running the production app.  Could you please assign the DNS name tacc-app.openskope.org to 129.114.16.73 for now?  Thanks!

**Comment by tmcphillips** [comment]
The production application is now running on tacc-app.openskope.org. A new CNAME record for app.openskope.org makes it an alias for tacc-app.
